- name: Git checkout
  git:
    repo: "https://github.com/{{ git_user }}/{{ git_repo }}.git"
    dest: "{{ home_dir }}/{{ git_repo }}"

# bk
- name: Copy
  copy:
    src: "{{ home_dir }}/webapp"
    dest: "{{ home_dir }}/.bk"
    remote_src: yes
  ignore_errors: yes

# remove
- name: remove
  file: 
    path: "{{ home_dir }}/webapp"
    state: absent
  
- name: remove
  file: 
    path: "{{ home_dir }}/README.md"
    state: absent

- name: remove
  file: 
    path: "{{ home_dir }}/.github"
    state: absent
  
- name: remove
  file: 
    path: "{{ home_dir }}/ansible"
    state: absent

- name: Copy
  copy:
    src: "{{ home_dir }}/{{ git_repo }}/*"
    dest: "{{ home_dir }}/"
    owner: isucon
    group: isucon
    remote_src: yes
  ignore_errors: yes

- name: Copy
  copy:
    src: "{{ home_dir }}/{{ git_repo }}/.github"
    dest: "{{ home_dir }}/"
    owner: isucon
    group: isucon
    remote_src: yes
  ignore_errors: yes

- name: remove
  file: 
    path: "{{ home_dir }}/{{ git_repo }}"
    state: absent

### Execute as login shell
# - name: setup
#   shell: sudo -u isucon bash -lc "sh setup.sh"
#   args:
#     chdir: "{{ home_dir }}/{{ isu_dir_name }}/webapp/golang/"

- name: isupipe-go is restarted
  systemd:
    name: isupipe-go
    state: restarted

- name: remove
  file: 
    path: /var/log/nginx/access.log
    state: absent

- name: nginx is restarted
  systemd:
    name: nginx
    state: restarted

- name: remove
  file: 
    path: /var/log/mysql/mysql-slow.sql
    state: absent

#- name: chmod
#  file: 
#    path: "{{ home_dir }}/{{ isu_dir_name }}/webapp/sql/init.sh"
#    mode: '0755'
#  ignore_errors: yes

#- name: shell
#  shell: "sh {{ home_dir }}/{{ isu_dir_name }}/webapp/sql/init.sh"
#  ignore_errors: yes

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted

# - name: redis is restarted
#   systemd:
#     name: redis-server
#     state: restarted
#   ignore_errors: yes