name: 'Pprof'
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
jobs:
  Pprof:
    name: "Pprof Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Exe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST1 }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sleep 7
            sudo curl -o cpu.pprof http://localhost:6060/debug/pprof/profile?seconds=60